status = [
  "build-and-check-ubuntu-64bit",
  "build-and-check-ubuntu-32bit",
  "build-and-check-gcc-48",
  "check-commit-changelogs",
  "check-commit-prefixes",
  "check-commit-signoffs",
]
# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
